// DO CHANGE THE PATHS

/* JAVA PATHS HAVE 2 SLASHES WHILE SQL PATHS HAVE 8 SLASHES ..........
* SQL PATH FORMATION HAS 14 SLASHES WHICH COMBINE WITH ALREADY PRESENT ONE AND MAKE 8 SLASKES AGAIN 
*/

import java.awt.Toolkit;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author meetmate
 */
public class sell_books extends javax.swing.JFrame {
int rsxValue=0;
String path_sql="D:\\\\\\\\\\\\\\\\Soft_Wares\\\\\\\\\\\\\\\\Netbeans\\\\\\\\\\\\\\\\NetBeans 8.2\\\\\\\\\\\\\\\\Projects\\\\\\\\\\\\\\\\BarterSystem\\\\\\\\\\\\\\\\BarterSystem\\\\\\\\\\\\\\\\src\\\\\\\\\\\\\\\\Pics\\\\\\\\\\\\\\\\def_bkPic.jpg";
String path_java="D:\\Soft_Wares\\Netbeans\\NetBeans 8.2\\Projects\\BarterSystem\\BarterSystem\\src\\Pics\\def_bkPic.jpg";
mysqlConnector my = new mysqlConnector();
String usr_Name="this";

    /**
     * Creates new form sell_books
     */
    public sell_books() {
        initComponents();
        picTxt.setEditable(false);
        uNameTransfer t = new uNameTransfer();
       
    try {
        usr_Name = t.getUName();
    } catch (SQLException ex) {
        Logger.getLogger(sell_books.class.getName()).log(Level.SEVERE, null, ex);
    }
    bkPicLb.setIcon(new ImageIcon(path_java));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        bkTxt = new javax.swing.JTextField();
        bkPicLb = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        authTxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        rsxCb = new javax.swing.JComboBox<>();
        rsxLb = new javax.swing.JLabel();
        rsxTxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        browse = new javax.swing.JButton();
        post = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        picTxt = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("POST A BOOK");
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Pics/logo.jpg")));
        setMaximumSize(new java.awt.Dimension(1440, 860));
        setMinimumSize(new java.awt.Dimension(1440, 860));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel1.setText("NAME OF THE BOOK");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(82, 103, 212, 29);

        bkTxt.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        bkTxt.setMinimumSize(new java.awt.Dimension(10, 27));
        getContentPane().add(bkTxt);
        bkTxt.setBounds(550, 100, 263, 40);

        bkPicLb.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        bkPicLb.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bkPicLb.setMaximumSize(new java.awt.Dimension(96, 84));
        bkPicLb.setMinimumSize(new java.awt.Dimension(96, 84));
        bkPicLb.setPreferredSize(new java.awt.Dimension(96, 84));
        getContentPane().add(bkPicLb);
        bkPicLb.setBounds(90, 600, 96, 84);

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel3.setText("AUTHOR OF THE BOOK");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(82, 205, 243, 29);

        authTxt.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        authTxt.setMinimumSize(new java.awt.Dimension(10, 27));
        getContentPane().add(authTxt);
        authTxt.setBounds(550, 190, 263, 40);

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel4.setText("RENT / SELL / EXCHANGE THE BOOK");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(82, 307, 390, 29);

        rsxCb.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        rsxCb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "RENT", "SELL", "EXCHANGE" }));
        rsxCb.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rsxCbItemStateChanged(evt);
            }
        });
        getContentPane().add(rsxCb);
        rsxCb.setBounds(560, 300, 141, 40);

        rsxLb.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        rsxLb.setText("Rent book for (days)");
        getContentPane().add(rsxLb);
        rsxLb.setBounds(82, 407, 470, 29);

        rsxTxt.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        rsxTxt.setMinimumSize(new java.awt.Dimension(10, 27));
        getContentPane().add(rsxTxt);
        rsxTxt.setBounds(560, 400, 206, 40);

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel6.setText("BROWSE FOR A PIC");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(82, 509, 201, 29);

        browse.setFont(new java.awt.Font("Trebuchet MS", 0, 20)); // NOI18N
        browse.setText("BROWSE...");
        browse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseActionPerformed(evt);
            }
        });
        getContentPane().add(browse);
        browse.setBounds(1000, 520, 127, 33);

        post.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        post.setText("POST");
        post.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                postActionPerformed(evt);
            }
        });
        getContentPane().add(post);
        post.setBounds(1160, 690, 184, 37);

        picTxt.setColumns(20);
        picTxt.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        picTxt.setRows(2);
        picTxt.setText("SET THE DEFAULT PICTURE");
        jScrollPane1.setViewportView(picTxt);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(560, 500, 400, 60);

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        jLabel5.setText("POST A BOOK");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(1140, 20, 224, 42);

        jMenuBar1.setMargin(new java.awt.Insets(0, 1060, 0, 0));
        jMenuBar1.setPreferredSize(new java.awt.Dimension(55, 30));

        jMenu6.setText("SELLER'S ZONE   ");
        jMenu6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu6.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N

        jMenuItem2.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jMenuItem2.setText("Your Books");
        jMenuItem2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem2);

        jMenuBar1.add(jMenu6);

        jMenu1.setText("ACCOUNT");
        jMenu1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu1.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N

        jMenuItem3.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jMenuItem3.setText("Your Bids");
        jMenuItem3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem4.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jMenuItem4.setText("Inbox");
        jMenuItem4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuItem5.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jMenuItem5.setText("Sent Mail");
        jMenuItem5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuItem6.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jMenuItem6.setText("Compose");
        jMenuItem6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem6);

        jMenuItem7.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jMenuItem7.setText("Account Settings");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem7);

        jMenuItem8.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jMenuItem8.setText("Log Out");
        jMenuItem8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem8);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Go To Home");
        jMenu2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu2.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jMenu2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jMenu2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenu2.setMargin(new java.awt.Insets(0, 20, 0, 0));
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        sellers_books g = new sellers_books();
        g.setVisible(true);
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        your_bids g = new your_bids();
        g.setVisible(true);
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        Inbox g = new Inbox();
        g.setVisible(true);
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        Sent g = new Sent();
        g.setVisible(true);
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        Compose g = new Compose();
        g.setVisible(true);
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        WelcomeScreen g = new WelcomeScreen();
        g.setVisible(true);
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        barter_ground g = new barter_ground();
        g.setVisible(true);
        this.setVisible(false);          // TODO add your handling code here:
    }//GEN-LAST:event_jMenu2MouseClicked

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
   account_settings g = new account_settings();
        g.setVisible(true);
        this.setVisible(false);      // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void postActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_postActionPerformed
// ******************** CHECKING WHETHER ALL THE FIELDS ARE SELECTED OR NOT *******************
if (bkTxt.getText().isEmpty()||authTxt.getText().isEmpty()||rsxTxt.getText().isEmpty())
    JOptionPane.showMessageDialog(rootPane, "PLEASE FILL ALL THE DETAILS","ERROR",0);
else{
ResultSet res=null;
String rer="D%",ret="D";

switch(rsxValue){
    case 0 : rer="R%"; ret="R";  break;
    case 1 : rer="S%"; ret="S"; break;
    case 2 : rer="X%"; ret="X"; break;        
}

int total_num=1;
res=my.getResultSetFor("select count(stockID) from stockdetails where stockID like '"+rer+"' ");
    try {
        if(res.next()) total_num=Integer.parseInt(res.getString("count(stockID)"))+1;
    } catch (SQLException ex) {
        Logger.getLogger(sell_books.class.getName()).log(Level.SEVERE, null, ex);
    }
 // ********************** CREATING STOCKID ****************************
 String final_stockID="D003";
 if (total_num<=9) final_stockID = ""+ret+"00"+total_num;
else if (total_num<=99) final_stockID = ""+ret+"0"+total_num;   
else final_stockID = ""+ret+total_num;
 // *********************************************************************
 
 


my.setSQLUpdate("insert into stockdetails values ('"+final_stockID+"','"+bkTxt.getText()+"','"+usr_Name+"','"+authTxt.getText()+"','"+ret+"','"+rsxTxt.getText()+"','"+path_sql+"');");
 JOptionPane.showMessageDialog(rootPane, "YOU HAVE SUCCESSFULLY POSTED A BOOK!!!","DONE",1);
 
//<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<setting defaults again>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
 bkTxt.setText("");
 authTxt.setText("");
 rsxTxt.setText("");
 picTxt.setText("SET THE DEFAULT PICTURE");
path_sql="D:\\\\\\\\\\\\\\\\Soft_Wares\\\\\\\\\\\\\\\\Netbeans\\\\\\\\\\\\\\\\NetBeans 8.2\\\\\\\\\\\\\\\\Projects\\\\\\\\\\\\\\\\BarterSystem\\\\\\\\\\\\\\\\BarterSystem\\\\\\\\\\\\\\\\src\\\\\\\\\\\\\\\\Pics\\\\\\\\\\\\\\\\def_bkPic.jpg";
 path_java="D:\\Soft_Wares\\Netbeans\\NetBeans 8.2\\Projects\\BarterSystem\\BarterSystem\\src\\Pics\\def_bkPic.jpg";
 bkPicLb.setIcon(new ImageIcon(path_java));
}
    }//GEN-LAST:event_postActionPerformed

    private void rsxCbItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rsxCbItemStateChanged
 switch(rsxCb.getSelectedIndex()){
     case 0: rsxLb.setText("Rent book for (days)"); rsxTxt.setVisible(true); rsxValue=0;  break;
     case 1: rsxLb.setText("Selling Price"); rsxTxt.setVisible(true); rsxValue=1; break;
     case 2: rsxLb.setText("Read our T&C's for exchange of books"); rsxTxt.setVisible(false); rsxValue=2; break;
 }         // TODO add your handling code here:
    }//GEN-LAST:event_rsxCbItemStateChanged

    private void browseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseActionPerformed
JFileChooser selectFile = new javax.swing.JFileChooser();
selectFile.setDialogType(javax.swing.JFileChooser.OPEN_DIALOG);
selectFile.setApproveButtonText("Select");
selectFile.setApproveButtonToolTipText("");
selectFile.setCurrentDirectory(new java.io.File("D:\\meetm\\Pictures"));
selectFile.setDialogTitle("SELECT PICTURE OF THE BOOK");
selectFile.setFileSelectionMode(javax.swing.JFileChooser.FILES_AND_DIRECTORIES);

int check = selectFile.showDialog(this, "SELECT");

if(check==JFileChooser.APPROVE_OPTION){
 // CHECKING WHETHER THE SELECTED FILE IS .jpg OR .png
 
 if(selectFile.getSelectedFile().getAbsolutePath().contains(".jpg")||selectFile.getSelectedFile().getAbsolutePath().contains(".png")||selectFile.getSelectedFile().getAbsolutePath().contains(".jpeg")){
     path_java = selectFile.getSelectedFile().getAbsolutePath();
    picTxt.setText(path_java);
    bkPicLb.setIcon(new ImageIcon(path_java));
    // ***************** Modifying the string *************************
    int i=-7;
    path_sql=path_java; // java path is transferred to sql path path which then goes through the loop to become a sql path.... in other words, java path is made into sql path without modifying the info in java path.
    StringBuilder str = new StringBuilder(path_sql);
    while((i=(path_sql.indexOf("\\",i+7))+1)>0){    
        path_sql=str.insert(i,"\\\\\\\\\\\\\\").toString();
    }
   
}

 // IF USER DIDN'T SELECT A PICTURE ********************************
else  JOptionPane.showMessageDialog(rootPane, "PLEASE SELECT A PICTURE FILE","ERROR",0); 
}
else if (check==JFileChooser.CANCEL_OPTION||check==JFileChooser.ERROR_OPTION){
     System.out.println("in else");
     System.out.println(path_sql);
path_sql="D:\\\\\\\\\\\\\\\\Soft_Wares\\\\\\\\\\\\\\\\Netbeans\\\\\\\\\\\\\\\\NetBeans 8.2\\\\\\\\\\\\\\\\Projects\\\\\\\\\\\\\\\\BarterSystem\\\\\\\\\\\\\\\\BarterSystem\\\\\\\\\\\\\\\\src\\\\\\\\\\\\\\\\Pics\\\\\\\\\\\\\\\\def_bkPic.jpg";
path_java="D:\\Soft_Wares\\Netbeans\\NetBeans 8.2\\Projects\\BarterSystem\\BarterSystem\\src\\Pics\\def_bkPic.jpg";
 picTxt.setText("SET THE DEFAULT PICTURE");
 bkPicLb.setIcon(new ImageIcon(path_java));
}
    }//GEN-LAST:event_browseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sell_books.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sell_books.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sell_books.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sell_books.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new sell_books().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField authTxt;
    private javax.swing.JLabel bkPicLb;
    private javax.swing.JTextField bkTxt;
    private javax.swing.JButton browse;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea picTxt;
    private javax.swing.JButton post;
    private javax.swing.JComboBox<String> rsxCb;
    private javax.swing.JLabel rsxLb;
    private javax.swing.JTextField rsxTxt;
    // End of variables declaration//GEN-END:variables
}
