/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
/**
 *
 * @author meetm
 */
public class sellers_books extends javax.swing.JFrame {
int rsxValue=0;
String path_sql="D:\\\\\\\\\\\\\\\\Soft_Wares\\\\\\\\\\\\\\\\Netbeans\\\\\\\\\\\\\\\\NetBeans 8.2\\\\\\\\\\\\\\\\Projects\\\\\\\\\\\\\\\\BarterSystem\\\\\\\\\\\\\\\\BarterSystem\\\\\\\\\\\\\\\\src\\\\\\\\\\\\\\\\Pics\\\\\\\\\\\\\\\\def_bkPic.jpg";
String path_java="D:\\Soft_Wares\\Netbeans\\NetBeans 8.2\\Projects\\BarterSystem\\BarterSystem\\src\\Pics\\def_bkPic.jpg";
mysqlConnector my = new mysqlConnector();
    /**
     * Creates new form sellers_books
     */
    public sellers_books() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        xtraInfo = new javax.swing.JFrame();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        browse = new javax.swing.JButton();
        rsxCb = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        authTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        rsxTxt = new javax.swing.JTextField();
        rsxLb = new javax.swing.JLabel();
        bkTxt = new javax.swing.JTextField();
        bkPicLb = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        picTxt = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        xtraInfo.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        xtraInfo.setTitle("QUERIES");
        xtraInfo.setMinimumSize(new java.awt.Dimension(776, 557));
        xtraInfo.setSize(new java.awt.Dimension(776, 557));

        javax.swing.GroupLayout xtraInfoLayout = new javax.swing.GroupLayout(xtraInfo.getContentPane());
        xtraInfo.getContentPane().setLayout(xtraInfoLayout);
        xtraInfoLayout.setHorizontalGroup(
            xtraInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 776, Short.MAX_VALUE)
        );
        xtraInfoLayout.setVerticalGroup(
            xtraInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 557, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("YOUR BOOKS");
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Pics/logo.jpg")));
        setMaximumSize(new java.awt.Dimension(1440, 860));
        setMinimumSize(new java.awt.Dimension(1440, 860));
        setPreferredSize(new java.awt.Dimension(1440, 860));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 0, 36)); // NOI18N
        jLabel1.setText("YOUR BOOKS");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(1170, 30, 206, 42);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "BOOK_ID", "BOOK_NAME", "R/S/X", "INFO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(880, 90, 529, 660);

        jButton1.setFont(new java.awt.Font("Trebuchet MS", 0, 20)); // NOI18N
        jButton1.setText("VIEW INFO");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(330, 730, 140, 33);

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel6.setText("Browse for a pic");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(30, 510, 174, 29);

        browse.setFont(new java.awt.Font("Trebuchet MS", 0, 20)); // NOI18N
        browse.setText("BROWSE...");
        browse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseActionPerformed(evt);
            }
        });
        getContentPane().add(browse);
        browse.setBounds(700, 600, 127, 33);

        rsxCb.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        rsxCb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "RENT", "SELL", "EXCHANGE" }));
        rsxCb.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rsxCbItemStateChanged(evt);
            }
        });
        getContentPane().add(rsxCb);
        rsxCb.setBounds(500, 300, 141, 40);

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel4.setText("Rent / Sell / eXchange the book");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 310, 346, 29);

        authTxt.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        authTxt.setMinimumSize(new java.awt.Dimension(10, 27));
        getContentPane().add(authTxt);
        authTxt.setBounds(500, 190, 263, 40);

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel3.setText("Author of the book");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 210, 202, 29);

        rsxTxt.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        rsxTxt.setMinimumSize(new java.awt.Dimension(10, 27));
        getContentPane().add(rsxTxt);
        rsxTxt.setBounds(500, 400, 206, 40);

        rsxLb.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        rsxLb.setText("Rent book for (days)");
        getContentPane().add(rsxLb);
        rsxLb.setBounds(30, 410, 470, 29);

        bkTxt.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        bkTxt.setMinimumSize(new java.awt.Dimension(10, 27));
        getContentPane().add(bkTxt);
        bkTxt.setBounds(500, 100, 263, 40);

        bkPicLb.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        bkPicLb.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bkPicLb.setMaximumSize(new java.awt.Dimension(96, 84));
        bkPicLb.setMinimumSize(new java.awt.Dimension(96, 84));
        bkPicLb.setPreferredSize(new java.awt.Dimension(96, 84));
        getContentPane().add(bkPicLb);
        bkPicLb.setBounds(40, 600, 96, 84);

        picTxt.setColumns(20);
        picTxt.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        picTxt.setRows(2);
        picTxt.setText("SET THE DEFAULT PICTURE");
        jScrollPane2.setViewportView(picTxt);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(500, 500, 330, 60);

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel7.setText("Name of the book");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(30, 110, 191, 29);

        jButton2.setFont(new java.awt.Font("Trebuchet MS", 0, 20)); // NOI18N
        jButton2.setText("SAVE");
        getContentPane().add(jButton2);
        jButton2.setBounds(720, 730, 106, 33);

        jButton3.setFont(new java.awt.Font("Trebuchet MS", 0, 20)); // NOI18N
        jButton3.setText("EDIT");
        getContentPane().add(jButton3);
        jButton3.setBounds(40, 730, 73, 33);

        jMenuBar1.setMargin(new java.awt.Insets(0, 1060, 0, 0));
        jMenuBar1.setPreferredSize(new java.awt.Dimension(55, 30));

        jMenu6.setText("SELLER'S ZONE   ");
        jMenu6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu6.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N

        jMenuItem1.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jMenuItem1.setText("Sell/Rent/Exchange");
        jMenuItem1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem1);

        jMenuBar1.add(jMenu6);

        jMenu1.setText("ACCOUNT");
        jMenu1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu1.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N

        jMenuItem3.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jMenuItem3.setText("Your Bids");
        jMenuItem3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem4.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jMenuItem4.setText("Inbox");
        jMenuItem4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuItem5.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jMenuItem5.setText("Sent Mail");
        jMenuItem5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuItem6.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jMenuItem6.setText("Compose");
        jMenuItem6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem6);

        jMenuItem2.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jMenuItem2.setText("Account Settings");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem8.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jMenuItem8.setText("Log Out");
        jMenuItem8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem8);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Go To Home");
        jMenu2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu2.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jMenu2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jMenu2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenu2.setMargin(new java.awt.Insets(0, 20, 0, 0));
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        sell_books g = new sell_books();
        g.setVisible(true);
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        your_bids g = new your_bids();
        g.setVisible(true);
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        Inbox g = new Inbox();
        g.setVisible(true);
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        Sent g = new Sent();
        g.setVisible(true);
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        Compose g = new Compose();
        g.setVisible(true);
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        WelcomeScreen g = new WelcomeScreen();
        g.setVisible(true);
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        barter_ground g = new barter_ground();
        g.setVisible(true);
        this.setVisible(false);          // TODO add your handling code here:
    }//GEN-LAST:event_jMenu2MouseClicked

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
account_settings g = new account_settings();
        g.setVisible(true);
        this.setVisible(false);          // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void browseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseActionPerformed
        JFileChooser selectFile = new javax.swing.JFileChooser();
        selectFile.setDialogType(javax.swing.JFileChooser.OPEN_DIALOG);
        selectFile.setApproveButtonText("Select");
        selectFile.setApproveButtonToolTipText("");
        selectFile.setCurrentDirectory(new java.io.File("D:\\meetm\\Pictures"));
        selectFile.setDialogTitle("SELECT PICTURE OF THE BOOK");
        selectFile.setFileSelectionMode(javax.swing.JFileChooser.FILES_AND_DIRECTORIES);

        int check = selectFile.showDialog(this, "SELECT");

        if(check==JFileChooser.APPROVE_OPTION){
            // CHECKING WHETHER THE SELECTED FILE IS .jpg OR .png

            if(selectFile.getSelectedFile().getAbsolutePath().contains(".jpg")||selectFile.getSelectedFile().getAbsolutePath().contains(".png")||selectFile.getSelectedFile().getAbsolutePath().contains(".jpeg")){
                path_java = selectFile.getSelectedFile().getAbsolutePath();
                picTxt.setText(path_java);
                bkPicLb.setIcon(new ImageIcon(path_java));
                // ***************** Modifying the string *************************
                int i=-7;
                path_sql=path_java; // java path is transferred to sql path path which then goes through the loop to become a sql path.... in other words, java path is made into sql path without modifying the info in java path.
                StringBuilder str = new StringBuilder(path_sql);
                while((i=(path_sql.indexOf("\\",i+7))+1)>0){    
                    path_sql=str.insert(i,"\\\\\\\\\\\\\\").toString();
                    }

                }

                // IF USER DIDN'T SELECT A PICTURE ********************************
                else  JOptionPane.showMessageDialog(rootPane, "PLEASE SELECT A PICTURE FILE","ERROR",0);
            }
            else if (check==JFileChooser.CANCEL_OPTION||check==JFileChooser.ERROR_OPTION){
                System.out.println("in else");
                System.out.println(path_sql);
                path_sql="D:\\\\\\\\\\\\\\\\Soft_Wares\\\\\\\\\\\\\\\\Netbeans\\\\\\\\\\\\\\\\NetBeans 8.2\\\\\\\\\\\\\\\\Projects\\\\\\\\\\\\\\\\BarterSystem\\\\\\\\\\\\\\\\BarterSystem\\\\\\\\\\\\\\\\src\\\\\\\\\\\\\\\\Pics\\\\\\\\\\\\\\\\def_bkPic.jpg";
                path_java="D:\\Soft_Wares\\Netbeans\\NetBeans 8.2\\Projects\\BarterSystem\\BarterSystem\\src\\Pics\\def_bkPic.jpg";
                picTxt.setText("SET THE DEFAULT PICTURE");
                bkPicLb.setIcon(new ImageIcon(path_java));
            }
    }//GEN-LAST:event_browseActionPerformed

    private void rsxCbItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rsxCbItemStateChanged
        switch(rsxCb.getSelectedIndex()){
            case 0: rsxLb.setText("Rent book for (days)"); rsxTxt.setVisible(true); rsxValue=0;  break;
            case 1: rsxLb.setText("Selling Price"); rsxTxt.setVisible(true); rsxValue=1; break;
            case 2: rsxLb.setText("Read our T&C's for exchange of books"); rsxTxt.setVisible(false); rsxValue=2; break;
        }         // TODO add your handling code here:
    }//GEN-LAST:event_rsxCbItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
xtraInfo.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sellers_books.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sellers_books.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sellers_books.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sellers_books.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new sellers_books().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField authTxt;
    private javax.swing.JLabel bkPicLb;
    private javax.swing.JTextField bkTxt;
    private javax.swing.JButton browse;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea picTxt;
    private javax.swing.JComboBox<String> rsxCb;
    private javax.swing.JLabel rsxLb;
    private javax.swing.JTextField rsxTxt;
    private javax.swing.JFrame xtraInfo;
    // End of variables declaration//GEN-END:variables
}
