
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author DAV
 */
public class signup extends javax.swing.JFrame {
String pic=pic="D:\\\\\\\\\\\\\\\\Soft_Wares\\\\\\\\\\\\\\\\Netbeans\\\\\\\\\\\\\\\\NetBeans 8.2\\\\\\\\\\\\\\\\Projects\\\\\\\\\\\\\\\\BarterSystem\\\\\\\\\\\\\\\\BarterSystem\\\\\\\\\\\\\\\\src\\\\\\\\\\\\\\\\Pics\\\\\\\\\\\\\\\\default.png";

    /**
     * Creates new form signup
     */
    public signup() {
        initComponents();
        bkPicLb.setIcon(new ImageIcon(pic));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jname = new javax.swing.JTextField();
        jusname = new javax.swing.JTextField();
        jcn = new javax.swing.JTextField();
        jpw = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        browse = new javax.swing.JButton();
        bkPicLb = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SIGN UP");
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Pics/logo.jpg")));
        setMinimumSize(new java.awt.Dimension(1440, 860));
        setPreferredSize(new java.awt.Dimension(1440, 860));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 3, 56)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SIGN UP");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(590, 40, 297, 66);

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 30)); // NOI18N
        jLabel2.setText("NAME");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(300, 180, 79, 36);

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 30)); // NOI18N
        jLabel3.setText("USERNAME (7-20 CHARACTERS)");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(300, 260, 437, 36);

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 1, 30)); // NOI18N
        jLabel6.setText("CONTACT NO");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(300, 330, 183, 36);

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 1, 30)); // NOI18N
        jLabel8.setText("PASSWORD");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(300, 420, 153, 36);

        jButton1.setFont(new java.awt.Font("Trebuchet MS", 3, 30)); // NOI18N
        jButton1.setText("CREATE ACCOUNT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(580, 730, 289, 45);

        jname.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jname.setMinimumSize(new java.awt.Dimension(59, 20));
        getContentPane().add(jname);
        jname.setBounds(1010, 190, 179, 36);

        jusname.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jusname.setMinimumSize(new java.awt.Dimension(59, 20));
        getContentPane().add(jusname);
        jusname.setBounds(1010, 260, 179, 36);

        jcn.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jcn.setMinimumSize(new java.awt.Dimension(59, 20));
        getContentPane().add(jcn);
        jcn.setBounds(1010, 340, 179, 36);

        jpw.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jpw.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        getContentPane().add(jpw);
        jpw.setBounds(1010, 420, 180, 36);

        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 1, 30)); // NOI18N
        jLabel9.setText("PROFILE PICTURE");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(300, 490, 243, 36);

        browse.setFont(new java.awt.Font("Trebuchet MS", 3, 24)); // NOI18N
        browse.setText("BROWSE...");
        browse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseActionPerformed(evt);
            }
        });
        getContentPane().add(browse);
        browse.setBounds(1010, 500, 190, 37);

        bkPicLb.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bkPicLb.setMaximumSize(new java.awt.Dimension(104, 127));
        bkPicLb.setMinimumSize(new java.awt.Dimension(104, 127));
        bkPicLb.setPreferredSize(new java.awt.Dimension(104, 127));
        getContentPane().add(bkPicLb);
        bkPicLb.setBounds(310, 560, 104, 127);

        jMenuBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jMenuBar1.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        jMenuBar1.setMargin(new java.awt.Insets(0, 1275, 0, 0));

        jMenu1.setText("Go To Home");
        jMenu1.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jMenu1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jMenu1.setMargin(new java.awt.Insets(0, 20, 0, 0));
        jMenu1.setMinimumSize(new java.awt.Dimension(1440, 860));
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
if(jname.getText().isEmpty()||jusname.getText().isEmpty()||jcn.getText().isEmpty()||jpw.getText().isEmpty()) JOptionPane.showMessageDialog(rootPane, "PLEASE FILL ALL THE DETIALS","ERROR",0); 
else { 
String a=jname.getText();
String b=jusname.getText();
String contact=jcn.getText();
String p=jpw.getText();
mysqlConnector my = new mysqlConnector();
try{   
  my.setSQLUpdate("insert into usrdetails values ('"+a+"', '"+b+"','"+contact+"','"+p+"','"+pic+"');");    
}
 catch (Exception e)
 {
 JOptionPane.showMessageDialog(null,e);
 }
finally{
JOptionPane.showMessageDialog(rootPane, "You have successfully created an account!","DONE!",1);
WelcomeScreen r = new WelcomeScreen();
r.setVisible(true);
this.setVisible(false);
}
    }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
  WelcomeScreen g = new WelcomeScreen();
g.setVisible(true);
this.setVisible(false);      // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1MouseClicked

    private void browseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseActionPerformed
        JFileChooser selectFile = new javax.swing.JFileChooser();
        selectFile.setDialogType(javax.swing.JFileChooser.OPEN_DIALOG);
        selectFile.setApproveButtonText("Select");
        selectFile.setCurrentDirectory(new java.io.File("D:\\meetm\\Pictures"));
        selectFile.setDialogTitle("SELECT A PROFILE PICTURE");
        selectFile.setFileSelectionMode(javax.swing.JFileChooser.FILES_AND_DIRECTORIES);

        int check = selectFile.showDialog(this, "SELECT");

        if(check==JFileChooser.APPROVE_OPTION){
        // CHECKING WHETHER THE SELECTED FILE IS .jpg OR .png
       if(selectFile.getSelectedFile().getAbsolutePath().contains(".jpg")||selectFile.getSelectedFile().getAbsolutePath().contains(".png")||selectFile.getSelectedFile().getAbsolutePath().contains(".jpeg")){          
           pic=selectFile.getSelectedFile().getAbsolutePath();
           bkPicLb.setIcon(new ImageIcon(pic));
                // ***************** Modifying the string *************************
                int i=-7;                
                StringBuilder str = new StringBuilder(pic);
                while((i=(pic.indexOf("\\",i+7))+1)>0){    
                    pic=str.insert(i,"\\\\\\\\\\\\\\").toString();
                    }
                }

                // IF USER DIDN'T SELECT A PICTURE ********************************
                else  JOptionPane.showMessageDialog(rootPane, "PLEASE SELECT A PICTURE FILE","ERROR",0);
            }
            else if (check==JFileChooser.CANCEL_OPTION||check==JFileChooser.ERROR_OPTION){
                
                pic="D:\\\\\\\\\\\\\\\\Soft_Wares\\\\\\\\\\\\\\\\Netbeans\\\\\\\\\\\\\\\\NetBeans 8.2\\\\\\\\\\\\\\\\Projects\\\\\\\\\\\\\\\\BarterSystem\\\\\\\\\\\\\\\\BarterSystem\\\\\\\\\\\\\\\\src\\\\\\\\\\\\\\\\Pics\\\\\\\\\\\\\\\\default.png";
                
                bkPicLb.setIcon(new ImageIcon(pic));
            }
    }//GEN-LAST:event_browseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new signup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bkPicLb;
    private javax.swing.JButton browse;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JTextField jcn;
    private javax.swing.JTextField jname;
    private javax.swing.JPasswordField jpw;
    private javax.swing.JTextField jusname;
    // End of variables declaration//GEN-END:variables
}
