
import java.awt.Toolkit;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author DAV
 */
public class WelcomeScreen extends javax.swing.JFrame {
String usr_id = "";
    /**
     * Creates new form WelcomeScreen
     */
    public WelcomeScreen() {
        initComponents();
        pics.setIcon(new ImageIcon("src/Pics/pic1.jpg"));
        mysqlConnector my = new mysqlConnector();
        my.setSQLUpdate("delete from whoisonline;");
    }
    
    int p=1;

    /**
     *
     */
    public void left_btn(){
    leftlb.setBackground(new java.awt.Color(153, 153, 153));
        switch (p){
    case 1: pics.setIcon(new ImageIcon("src/Pics/pic5.jpg"));  p=5; break;
    case 2: pics.setIcon(new ImageIcon("src/Pics/pic1.jpg")); p-=1;  break;
    case 3: pics.setIcon(new ImageIcon("src/Pics/pic2.jpg")); p-=1;  break;
    case 4: pics.setIcon(new ImageIcon("src/Pics/pic3.jpg")); p-=1;  break;
    case 5: pics.setIcon(new ImageIcon("src/Pics/pic4.jpg"));p-=1;  break;
}  }

    /**
     *
     */
    public void right_btn()
        {
         rightlb.setBackground(new java.awt.Color(153, 153, 153));
        switch (p){
    case 1: pics.setIcon(new ImageIcon("src/Pics/pic2.jpg")); p+=1; break;
    case 2: pics.setIcon(new ImageIcon("src/Pics/pic3.jpg")); p+=1;  break;
    case 3: pics.setIcon(new ImageIcon("src/Pics/pic4.jpg")); p+=1;  break;
    case 4: pics.setIcon(new ImageIcon("src/Pics/pic5.jpg")); p+=1;  break;
    case 5: pics.setIcon(new ImageIcon("src/Pics/pic1.jpg")); p=1; break;
}
        }
    /**
     * This method is called from within the constructor to initialize the form.

     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        uname = new javax.swing.JTextField();
        pw = new javax.swing.JPasswordField();
        jPanel1 = new javax.swing.JPanel();
        pics = new javax.swing.JLabel();
        leftlb = new javax.swing.JLabel();
        rightlb = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("WELCOME");
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Pics/logo.jpg")));
        setMinimumSize(new java.awt.Dimension(1440, 860));
        setPreferredSize(new java.awt.Dimension(1440, 860));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 100)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("BARTER");
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(27, 62, 528, 96);

        jButton2.setFont(new java.awt.Font("Trebuchet MS", 3, 30)); // NOI18N
        jButton2.setText("Sign up !");
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(306, 769, 200, 41);

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel2.setText("Username");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(715, 69, 112, 29);

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel3.setText("Password");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(715, 153, 112, 29);

        uname.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        getContentPane().add(uname);
        uname.setBounds(945, 62, 237, 44);

        pw.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        pw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwActionPerformed(evt);
            }
        });
        getContentPane().add(pw);
        pw.setBounds(945, 146, 240, 43);

        jPanel1.setMinimumSize(new java.awt.Dimension(1221, 448));
        jPanel1.setPreferredSize(new java.awt.Dimension(1221, 448));

        pics.setMinimumSize(new java.awt.Dimension(1067, 438));
        pics.setPreferredSize(new java.awt.Dimension(1067, 438));

        leftlb.setBackground(new java.awt.Color(204, 204, 204));
        leftlb.setFont(new java.awt.Font("Trebuchet MS", 1, 96)); // NOI18N
        leftlb.setForeground(new java.awt.Color(255, 255, 255));
        leftlb.setText("<");
        leftlb.setOpaque(true);
        leftlb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                leftlbMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                leftlbMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                leftlbMouseExited(evt);
            }
        });

        rightlb.setBackground(new java.awt.Color(204, 204, 204));
        rightlb.setFont(new java.awt.Font("Trebuchet MS", 1, 96)); // NOI18N
        rightlb.setForeground(new java.awt.Color(255, 255, 255));
        rightlb.setText(">");
        rightlb.setOpaque(true);
        rightlb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rightlbMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                rightlbMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                rightlbMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(leftlb, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pics, javax.swing.GroupLayout.DEFAULT_SIZE, 1077, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rightlb, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pics, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(leftlb, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rightlb, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(95, 244, 1221, 448);

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel4.setText("Don't have an account?");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(27, 777, 261, 29);

        jButton3.setFont(new java.awt.Font("Trebuchet MS", 3, 30)); // NOI18N
        jButton3.setText("Guest");
        jButton3.setContentAreaFilled(false);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(1227, 769, 152, 41);

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel6.setText("Check out the items ready to get 'barter'ed as");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(703, 777, 520, 29);

        jButton1.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jButton1.setText("Login");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(1290, 50, 100, 150);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    signup g = new signup();
g.setVisible(true);
this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void leftlbMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_leftlbMouseEntered
    left_btn();  // TODO add your handling code here:
    }//GEN-LAST:event_leftlbMouseEntered

    private void rightlbMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rightlbMouseEntered
  right_btn();    // TODO add your handling code here:
    }//GEN-LAST:event_rightlbMouseEntered

    private void leftlbMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_leftlbMouseExited
    
  leftlb.setBackground(new java.awt.Color(204, 204, 204));
    }//GEN-LAST:event_leftlbMouseExited

    private void rightlbMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rightlbMouseExited
 rightlb.setBackground(new java.awt.Color(204, 204, 204));      // TODO add your handling code here:
    }//GEN-LAST:event_rightlbMouseExited

    private void leftlbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_leftlbMouseClicked
left_btn();        // TODO add your handling code here:
    }//GEN-LAST:event_leftlbMouseClicked

    private void rightlbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rightlbMouseClicked
right_btn();        // TODO add your handling code here:
    }//GEN-LAST:event_rightlbMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
String a=uname.getText();
String b=pw.getText();

try {
mysqlConnector my = new mysqlConnector();
ResultSet rs = my.getResultSetFor("select uNm from usrdetails where usrNm='"+a+"'&& usrPassword='"+b+"';");

if (rs.next())
{
 // SENDING USERNAME FROM THIS FRAME TO uNameTransfer.java
uNameTransfer t = new uNameTransfer();
t.sendUName(a);
//.........................................................
barter_ground d = new barter_ground();
d.setVisible(true);
this.setVisible(false);
}
else {
JOptionPane.showMessageDialog(rootPane, "INCORRECT USERNAME OR PASSWORD","ERROR",0);
}

}
catch (Exception e){
JOptionPane.showMessageDialog(null,e+"1");
}
 
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void pwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwActionPerformed
jButton1.doClick();        // TODO add your handling code here:
    }//GEN-LAST:event_pwActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WelcomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WelcomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WelcomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WelcomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WelcomeScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel leftlb;
    private javax.swing.JLabel pics;
    private javax.swing.JPasswordField pw;
    private javax.swing.JLabel rightlb;
    private javax.swing.JTextField uname;
    // End of variables declaration//GEN-END:variables
}
